name = "pascal-minus-one"
version = "0.1.0"
defaultTargets = ["PascalMinusOne"]

[[lean_lib]]
name = "PascalMinusOne"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "bd6c1abe5f55b6c3856172d6a23703e0888f5286"
