name = "pascal-minus-one"
version = "0.1.0"
defaultTargets = ["PascalMinusOne", "Challenge", "Solution"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "bd6c1abe5f55b6c3856172d6a23703e0888f5286"

[[lean_lib]]
name = "PascalMinusOne"

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]
