name: Palomar Predictive Preflight

on:
  push:
    branches: [palomar/package]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  palomar-prepare:
    uses: PalomarRegistry/PalomarSubmission/.github/workflows/submission.yml@a59f25bd8a66bf6faf3a4f4260d412989c0185ea
    with:
      repository: ${{ github.repository }}
      commit: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      pipeline_commit: a59f25bd8a66bf6faf3a4f4260d412989c0185ea
      request_id: pascalprep
      mode: preflight
      execution_profile: palomar-standard-v1
      options: '{"comparator_config_path":"comparator.json","authorization_relationship":"I am a responsible author or maintainer"}'

  palomar-full:
    needs: palomar-prepare
    uses: PalomarRegistry/PalomarSubmission/.github/workflows/submission.yml@a59f25bd8a66bf6faf3a4f4260d412989c0185ea
    with:
      repository: ${{ github.repository }}
      commit: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      pipeline_commit: a59f25bd8a66bf6faf3a4f4260d412989c0185ea
      request_id: pascalfull
      mode: full
      execution_profile: palomar-standard-v1
      options: '{"comparator_config_path":"comparator.json","authorization_relationship":"I am a responsible author or maintainer"}'
